### ISSUE TITLE
A question about the decoder

### ISSUE THREAD

**Issue by ekeronur** [psh01087/Vid-ODE#3]
Hi, thanks a lot for providing the code for this work. I have a question related to Decoder part of the study. In the paper, initial value h_s0 to the Conv-Decoder is set as h_t (latent representation of the input video produced by ODE-ConvGRU steps). However, from the following lines:
https://github.com/psh01087/Vid-ODE/blob/040f0ab19f3d840c1ffef53a0bcdf01fcd2fc444/models/conv_odegru.py#L107  
https://github.com/psh01087/Vid-ODE/blob/040f0ab19f3d840c1ffef53a0bcdf01fcd2fc444/models/conv_odegru.py#L200
https://github.com/psh01087/Vid-ODE/blob/040f0ab19f3d840c1ffef53a0bcdf01fcd2fc444/models/conv_odegru.py#L207 it seems like h_s0 is set as the Conv-Encoder features of first or last input image. Is there something that I am missing?

**Comment by psh01087** [comment]
Hi, Onur Eker.

We use the different values of the Conv-Decoder depending on the tasks
(i.e., video interpolation and extrapolation).
For the convenience of explanation, we only describe the video
extrapolation in the paper.
For video extrapolation, h_s0 is set as the Conv-Encoder features of the
last input image, but for video interpolation, h_s0 is set as the
Conv-Encoder features of the first input image.
This is because the first frame the optical flow is applied to depends on
the task.
In addition, we always concatenate the latent representation from ODE
decoder solver.

Thanks.

Best regards.

2021년 11월 4일 (목) 오후 2:48, Onur Eker ***@***.***>님이 작성:
